# This is a basic workflow to help you get started with Actions

name: Java Unit Tests

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      VERSION: 1.9.2

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'oracle' # See 'Supported distributions' for available options
          java-version: '17'

      # Runs a single command using the runners shell
      - name: Get Jar
        run: wget https://repo1.maven.org/maven2/org/junit/platform/junit-platform-console-standalone/$VERSION/junit-platform-console-standalone-$VERSION.jar
      - name: Compile
        run: javac -d compile_test src/core/*.java test/*.java -cp junit-platform-console-standalone-$VERSION.jar
      - name: Run Tests
        run: java -jar junit-platform-console-standalone-$VERSION.jar --class-path compile_test --select-class GameTest
